export enum TipoContatoActionsTypes {
  GET_ALL_TIPOCONTATO = "GET_ALL_TIPOCONTATO",
  GET_ALL_TIPOCONTATO_SUCCESS = "GET_ALL_TIPOCONTATO_SUCCESS",
  GET_ALL_TIPOCONTATO_FAILURE = "GET_ALL_TIPOCONTATO_FAILURE",
}
