export enum CategoriaActionsTypes {
  GET_ALL_CATEGORIAS = "GET_ALL_CATEGORIAS",
  GET_ALL_CATEGORIAS_SUCCESS = "GET_ALL_CATEGORIAS_SUCCESS",
  GET_ALL_CATEGORIAS_FAILURE = "GET_ALL_CATEGORIAS_FAILURE",
}
