export enum SubCategoriaActionsTypes {
  GET_SUBCATEGORIAS = "GET_SUBCATEGORIAS",
  GET_SUBCATEGORIAS_SUCCESS = "GET_SUBCATEGORIAS_SUCCESS",
  GET_SUBCATEGORIAS_FAILURE = "GET_SUBCATEGORIAS_FAILURE",
}
